server:
  port: 8083

spring:

  datasource:
    url: jdbc:h2:mem:invoiceDb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2