INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (1, 'Nikhil', 'chandigarh', null, '8427201407', '@email1', false );
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (2, 'Ani', 'Delhi', null, '8427201401','@email2', false );
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (3, 'Mni', 'Haryana', null, '8427201402','@email3', false );
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (4, 'Nni', 'Punjab', null, '8427201403','@email4', false );
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (5, 'Nun', 'Himachal', null, '8427201406','@email5', false );
INSERT INTO CUSTOMER (ID, NAME, ADDRESS, CUSTOMER_GST, PHONE_NUMBER, EMAIL, IS_BUSINESS_CUSTOMER) VALUES (6, 'Rin', 'Himachal', null, '8427201445','@email6', false );



